apiVersion: v1
kind: Service
metadata:
  name: kotlin-smtp
spec:
  selector:
    app: kotlin-smtp
  ports:
    - name: smtp
      port: 25
      targetPort: 2525
      protocol: TCP
    - name: metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
